name: squarespacedev
favicon: null
layout_spectrum: 0.8984342101030052
typography_spectrum: 0.8021357422694564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5433171545155346
  lightness: 0.9997867927886546
  saturation: 0.2978508973028511
  rhythmicContrast: 0.26361656887456775
purpose: []
